# Generated by Django 3.1.7 on 2021-04-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210405_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='web'),
        ),
    ]
