# Generated by Django 3.1.7 on 2021-04-09 11:39

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='default.jpg', upload_to='web'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='threeimage',
            field=versatileimagefield.fields.VersatileImageField(default='default.jpg', upload_to='web'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='twoimage',
            field=versatileimagefield.fields.VersatileImageField(default='default.jpg', upload_to='web'),
        ),
        migrations.AlterField(
            model_name='profileimg',
            name='profileimg',
            field=versatileimagefield.fields.VersatileImageField(default='prifiledummy.png', upload_to='profile'),
        ),
    ]
