# Generated by Django 3.1.7 on 2021-04-19 09:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210409_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detailDiscription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
