# Generated by Django 3.1.7 on 2021-04-19 09:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210419_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detailDiscription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
