# Generated by Django 3.1.7 on 2021-04-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210419_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='cover_image',
        ),
    ]
