# Generated by Django 3.1.7 on 2022-11-20 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210419_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(max_length=1000)),
                ('roomtype', models.CharField(max_length=200)),
                ('count', models.IntegerField(null=True)),
                ('rate', models.FloatField(max_length=200)),
                ('available_rooms', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('rate', models.FloatField(max_length=200)),
                ('room_no', models.IntegerField(null=True)),
                ('check_in', models.DateField(null=True)),
                ('check_out', models.DateField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.hotel')),
            ],
        ),
    ]
