# Generated by Django 3.1.7 on 2022-11-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_bookings_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
