# Generated by Django 3.1.7 on 2022-11-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20221120_0411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
