# Generated by Django 3.1.7 on 2022-11-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20221120_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rate',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
