# Generated by Django 3.1.7 on 2022-11-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20221120_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_no',
        ),
    ]
