# Generated by Django 3.1.7 on 2022-11-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_booking_room_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='count',
            new_name='room_count',
        ),
    ]
